language: r
cache: packages

addons:
  apt:
  packages:
  - libpoppler-cpp-dev

before_install:
  - Rscript -e 'install.packages(pkgs = c("Rpoppler"))'

warnings_are_errors: true

notifications:
  email:
  on_success: change
  on_failure: change
