language: r
cache: packages

addons:
  apt:
  packages:
  - libpoppler-glib-dev
  - poppler-utils

before_install:
  - Rscript -e 'install.packages(pkgs = c("Rpoppler"))'

warnings_are_errors: true

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'library(covr);codecov()'
