language: r
cache: packages

addons:
  apt:
  packages:
  - libpoppler-glib-dev
  - poppler-utils
  - libxml2-utils

before_install:
  - sudo apt-get install -y libpoppler-glib-dev poppler-utils libpoppler-cpp-dev
  - Rscript -e 'install.packages(pkgs = c("Rpoppler", "covr"))'

warnings_are_errors: false

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'library(covr);codecov(token = "d02e1347-6fa5-4be1-97d5-92a7326ee097")'
